uint64 timestamp

bool healthy

float32 errorscore

float32 mag_ratio
float32 gps_vel_ratio
float32 gps_pos_ratio
float32 gps_hgt_ratio
float32 baro_hgt_ratio
float32 rng_hgt_ratio
float32 yaw_mag_ratio
float32 yaw_ext_ratio
float32 tas_ratio
float32 ter_ratio
float32 vio_vel_ratio
float32 vio_pos_ratio
float32 vio_hgt_ratio
float32 of_vel_ratio

uint16 filterstatus
uint16 fusestatus
uint16 gps_check_flags

char[40] prearm_failing


